### Lecture 8 : Working with Data

In [2]:
import pandas as pd 

In [3]:
#import the file 
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/Cervical.csv')

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/data.csv')

In [5]:
#print the first 20 methods and attributes of df using the dir function
dir(df[:20])

['Age',
 'CholesterolAfter',
 'CholesterolBefore',
 'DOB',
 'Delta',
 'Group',
 'HR',
 'Name',
 'Smoke',
 'Survey',
 'T',
 'TAG',
 'Vocation',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__m

In [8]:
#use the head method to print the first five rows of the data fram
df.head()
df.tail()

Name         DOB  Age                        Vocation  Smoke  \
195     John Curtis  1936-11-25   66          Sales professional, IT      1   
196  Jessica Tanner  1986-07-01   54                       Paramedic      1   
197   Charles Smith  1959-01-30   61  Chartered certified accountant      0   
198    Barry Porter  1979-05-30   65                          Dancer      1   
199   Julie Barrett  1972-07-27   66              Theme park manager      1   

      HR  sBP  CholesterolBefore  TAG  Survey  CholesterolAfter  Delta  \
195   96  201               10.1  5.1       5              10.0    0.1   
196   93  183               10.1  5.3       5              10.0    0.1   
197   99  212               10.1  5.6       4               9.7    0.4   
198   98  200               10.1  5.3       3              10.0    0.1   
199  102  208               11.1  5.7       2              10.7    0.4   

       Group  
195  Control  
196  Control  
197  Control  
198  Control  
199   Active

In [9]:
#print the shape of df returns a tuple
df.shape

(200, 13)

In [10]:
#print the columns of df
df.columns

Index(['Name', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group'],
      dtype='object')

In [11]:
#print the number of dimensions of df
df.ndim

2

In [12]:
#print the type of df
df.dtypes

Name                  object
DOB                   object
Age                    int64
Vocation              object
Smoke                  int64
HR                     int64
sBP                    int64
CholesterolBefore    float64
TAG                  float64
Survey                 int64
CholesterolAfter     float64
Delta                float64
Group                 object
dtype: object

read up on pandas date and time objects

### Selecting Rows and Columns

In [13]:
#Assign the age column in df to the variable age_column
age_column = df['Age']

In [14]:
type(age_column)

pandas.core.series.Series

In [16]:
#Assign the age column in df to the variable age
age_column = df.Age

In [17]:
age_column.head()

0    43
1    53
2    33
3    43
4    46
Name: Age, dtype: int64

In [18]:
import numpy as np

In [19]:
age = age_column.to_numpy()

In [20]:
type(age)

numpy.ndarray

In [21]:
age

array([43, 53, 33, 43, 46, 48, 54, 58, 44, 31, 45, 35, 49, 56, 57, 38, 35,
       50, 45, 49, 63, 45, 51, 43, 31, 58, 40, 47, 45, 41, 47, 38, 54, 30,
       46, 64, 41, 40, 45, 65, 74, 55, 58, 53, 68, 54, 72, 32, 38, 59, 53,
       69, 42, 67, 38, 51, 37, 36, 34, 38, 31, 48, 49, 62, 39, 74, 41, 42,
       60, 67, 42, 74, 52, 37, 61, 54, 72, 36, 49, 47, 49, 49, 69, 43, 38,
       60, 45, 71, 65, 73, 60, 70, 45, 49, 65, 53, 30, 58, 50, 69, 72, 61,
       33, 30, 44, 71, 49, 75, 43, 35, 55, 38, 36, 46, 60, 40, 57, 69, 56,
       66, 60, 42, 49, 68, 32, 31, 56, 35, 63, 54, 68, 72, 40, 41, 66, 73,
       36, 54, 57, 74, 48, 72, 54, 71, 42, 54, 66, 58, 60, 63, 44, 55, 73,
       55, 40, 43, 71, 54, 61, 55, 67, 55, 68, 71, 54, 42, 53, 69, 57, 45,
       62, 33, 74, 74, 64, 43, 35, 57, 64, 55, 74, 50, 40, 62, 65, 63, 68,
       45, 41, 54, 62, 65, 72, 61, 70, 66, 54, 61, 65, 66])

In [22]:
#calculate the mean
age_column.mean()

53.07

In [23]:
age_column.min()

30

In [25]:
age_column.max()

75

In [27]:
age_column.describe()

count    200.000000
mean      53.070000
std       12.553207
min       30.000000
25%       43.000000
50%       54.000000
75%       64.000000
max       75.000000
Name: Age, dtype: float64

In [28]:
#display the first row of data in df using the oloc method-integer location
df.iloc[0]

Name                   Dylan Patton
DOB                      1981-10-07
Age                              43
Vocation             Energy manager
Smoke                             0
HR                               47
sBP                             145
CholesterolBefore               1.2
TAG                             1.2
Survey                            1
CholesterolAfter                0.7
Delta                           0.5
Group                        Active
Name: 0, dtype: object

In [31]:
#Select rows 2,5, and 7 iwith iloc
df.iloc[[1,4,6]]

Name         DOB  Age               Vocation  Smoke  HR  sBP  \
1    Sandra Howard  1993-01-27   53            Tax adviser      0  51  115   
4    Robert Wilson  1964-06-23   46  Clinical embryologist      0  61  138   
6  Frank Zimmerman  1981-03-04   54         Police officer      0  60  129   

   CholesterolBefore  TAG  Survey  CholesterolAfter  Delta   Group  
1                1.2  0.6       3               1.0    0.2  Active  
4                2.8  2.1       5               2.8    0.0  Active  
6                2.9  2.4       1               2.6    0.3  Active

In [32]:
#select the first two rows
df.iloc[0:2]

Name         DOB  Age        Vocation  Smoke  HR  sBP  \
0   Dylan Patton  1981-10-07   43  Energy manager      0  47  145   
1  Sandra Howard  1993-01-27   53     Tax adviser      0  51  115   

   CholesterolBefore  TAG  Survey  CholesterolAfter  Delta   Group  
0                1.2  1.2       1               0.7    0.5  Active  
1                1.2  0.6       3               1.0    0.2  Active

In [33]:
#extract the first five rows for the first and third coluns using iloc
df.iloc[:5, [0,2]]

Name  Age
0       Dylan Patton   43
1      Sandra Howard   53
2  Samantha Williams   33
3     Ashley Hensley   43
4      Robert Wilson   46

In [34]:
df.loc[:4, ['Name', 'Age']]

Name  Age
0       Dylan Patton   43
1      Sandra Howard   53
2  Samantha Williams   33
3     Ashley Hensley   43
4      Robert Wilson   46

### Filtering Data

In [35]:
#PRINT THE UNIQUE VALUES IN THE SMOKE COLUMN
df.Smoke.unique()

array([0, 2, 1])

In [36]:
#SELECRT THE AGES OF THOSE who do not smke and assign it to the variable age_nonsmokers
age_nonsmokers = df.loc[df.Smoke == 0]['Age'].to_numpy()
age_nonsmokers

array([43, 53, 33, 43, 46, 48, 54, 58, 44, 31, 45, 35, 49, 56, 57, 35, 50,
       49, 63, 45, 51, 40, 47, 41, 47, 38, 54, 30, 46, 64, 40, 45, 65, 55,
       53, 54, 72, 32, 38, 59, 53, 42, 38, 51, 37, 36, 48, 49, 62, 39, 74,
       42, 72, 61, 33, 30, 44, 71, 49, 75, 43, 55, 38, 36, 46, 60, 57, 69,
       56, 66, 60, 42, 32, 31, 56, 35, 63, 54, 68, 72, 40, 54, 62, 74, 62,
       41, 61, 61])

In [39]:
non_smokers_choice_3 = df.loc[(df.Smoke == 0) & (df.Survey ==3), 'Age']
non_smokers_choice_3

1      53
2      33
11     35
14     57
27     47
32     54
38     45
45     54
50     53
112    36
130    68
183    62
Name: Age, dtype: int64

In [40]:
crit = (df.Smoke == 0) | (df.Survey > 3)

In [44]:
jobs = ('IT consultant', 'Energy manager', 'Clinical embryologist')

In [45]:
crit = df.Vocation.isin(jobs)

In [46]:
df_jobs = df.loc[crit]
df_jobs

Name         DOB  Age               Vocation  Smoke  HR  \
0         Dylan Patton  1981-10-07   43         Energy manager      0  47   
2    Samantha Williams  1973-12-21   33          IT consultant      0  54   
4        Robert Wilson  1964-06-23   46  Clinical embryologist      0  61   
188        Joan Chavez  1999-10-07   41         Energy manager      0  93   

     sBP  CholesterolBefore  TAG  Survey  CholesterolAfter  Delta    Group  
0    145                1.2  1.2       1               0.7    0.5   Active  
2    120                2.0  1.3       3               1.7    0.3   Active  
4    138                2.8  2.1       5               2.8    0.0   Active  
188  182                9.1  5.0       2               8.8    0.3  Control

In [47]:
# Build a criterium with the str.contains method for the word manager
crit = df.Vocation.str.contains('manager', na=False) 

In [48]:
# Create a new dataframe object with the criterium and assign it to the variable df_manager
df_manager = df.loc[crit]
df_manager[:5]

Name         DOB  Age  \
0               Dylan Patton  1981-10-07   43   
34  Mr. Tyler Strickland DDS  1940-08-27   46   
54          Stephanie Jacobs  1977-06-18   38   
55              Juan Johnson  1956-12-09   51   
71             Tina Martinez  1941-05-31   74   

                              Vocation  Smoke  HR  sBP  CholesterolBefore  \
0                       Energy manager      0  47  145                1.2   
34  Tourist information centre manager      0  62  136                4.1   
54           Estate manager/land agent      0  69  139                4.4   
55  Logistics and distribution manager      0  65  141                4.5   
71         Passenger transport manager      1  69  146                4.8   

    TAG  Survey  CholesterolAfter  Delta    Group  
0   1.2       1               0.7    0.5   Active  
34  2.3       2               3.8    0.3  Control  
54  2.7       2               4.0    0.4   Active  
55  2.9       5               4.0    0.5  Control  
71  3.1       4               4.5    0.3   Active

In [49]:
# Replace the Name column with the Patient
df.rename(columns={'Name': 'Patient'}, inplace=True)
df.columns # Call the column names

Index(['Patient', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group'],
      dtype='object')